using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace ArvinRunner.EditorTools
{
    /// <summary>
    /// One-click project build. Creates the layers, placeholder art, tuning
    /// assets, prefabs, chunk library, levels and a fully wired Game scene.
    ///
    /// Safe to run more than once - it overwrites what it generated before.
    /// </summary>
    public static class ArvinRunnerSetup
    {
        private const string DataFolder = "Assets/Data";
        private const string PrefabFolder = "Assets/Prefabs";
        private const string LevelFolder = "Assets/Data/Levels";
        private const string ScenePath = "Assets/Scenes/Game.unity";
        private const string MenuScenePath = "Assets/Scenes/MainMenu.unity";

        [MenuItem("ArvinRunner/Build Playable Project", priority = 0)]
        public static void BuildAll()
        {
            if (!EditorUtility.DisplayDialog(
                    "Build ArvinRunner",
                    "This generates placeholder art, prefabs, levels and a new Game scene.\n\n" +
                    "Anything previously generated by this tool is overwritten. Continue?",
                    "Build", "Cancel"))
                return;

            try
            {
                EditorUtility.DisplayProgressBar("ArvinRunner", "Setting up layers", 0.05f);
                EditorUtil.EnsureLayers();
                ConfigureProject();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Generating placeholder art", 0.12f);
                PlaceholderArt.GenerateAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Importing artwork", 0.2f);
                ArtImport.ImportAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Importing player frames", 0.24f);
                PlayerAnimationImport.ImportAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Importing moving obstacles", 0.27f);
                MovingObstacleImport.ImportAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Importing audio", 0.3f);
                AudioImport.ImportAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Creating tuning assets", 0.3f);
                PlayerConfig config = CreatePlayerConfig();
                SpriteAnimationSet animations = CreateAnimationSet(config);
                ParallaxTheme night = CreateTheme("Theme_Night", new Color(0.05f, 0.06f, 0.13f), Color.white);
                ParallaxTheme dusk = CreateTheme("Theme_Dusk", new Color(0.16f, 0.09f, 0.14f),
                                                 new Color(1f, 0.82f, 0.72f));

                EditorUtility.DisplayProgressBar("ArvinRunner", "Building prefabs", 0.45f);
                TrickSet tricks = CreateTrickSet();
                GameObject player = CreatePlayerPrefab(config, animations, tricks);
                GameObject pad = CreatePadPrefab();
                GameObject finish = CreateFinishPrefab();
                GameObject killZone = CreateKillZonePrefab();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Building obstacle chunks", 0.6f);
                LevelChunk[] chunks = ChunkFactory.CreateAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Authoring levels", 0.75f);
                LevelSet campaign = CreateLevels(chunks, night, dusk);

                EditorUtility.DisplayProgressBar("ArvinRunner", "Assembling the game scene", 0.88f);
                BuildScene(player, pad, finish, killZone, campaign, night);

                EditorUtility.DisplayProgressBar("ArvinRunner", "Building the main menu", 0.95f);
                BuildMainMenuScene(campaign);

                SetBuildSettings(MenuScenePath, ScenePath);

                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            Debug.Log("[ArvinRunner] Build complete. MainMenu.unity is open - press Play to start there.");
            EditorUtility.DisplayDialog("ArvinRunner",
                "Done.\n\nAssets/Scenes/MainMenu.unity is open and ready - press Play.\n\n" +
                "Editor controls: W / Up / Space to jump, S / Down to slide, " +
                "or drag the mouse like a swipe.", "Play");
        }

        [MenuItem("ArvinRunner/Reset Saved Progress", priority = 20)]
        public static void ResetProgress()
        {
            SaveData.ResetAll();
            Debug.Log("[ArvinRunner] Saved progress cleared.");
        }

        // ================================================================= //
        // Project settings
        // ================================================================= //

        private static void ConfigureProject()
        {
            Physics2D.gravity = new Vector2(0f, -9.81f);
            Physics2D.queriesStartInColliders = false;

            PlayerSettings.defaultInterfaceOrientation = UIOrientation.LandscapeLeft;
            PlayerSettings.allowedAutorotateToPortrait = false;
            PlayerSettings.allowedAutorotateToPortraitUpsideDown = false;
        }

        // ================================================================= //
        // Assets
        // ================================================================= //

        private static PlayerConfig CreatePlayerConfig()
        {
            var config = ScriptableObject.CreateInstance<PlayerConfig>();
            return EditorUtil.CreateAsset(config, $"{DataFolder}/PlayerConfig.asset");
        }

        /// <summary>
        /// The runner's animation set, filled from the drawn frames in
        /// Art/Player/PlayerAnimations.
        ///
        /// Six clips were drawn and there are twelve slots, which is the useful
        /// part rather than a shortfall. A slot holding more than one frame plays
        /// as a flip-book and the procedural tricks stand down for it; a slot
        /// holding a single pose keeps the tricks, so the spins and squashes in
        /// TrickSet.asset still carry the vault, the wall run and the ledge work.
        /// Every slot below is therefore deliberate about which of the two it
        /// wants - see PlayerAnimatorDriver.TricksAllowed.
        ///
        /// Frame rates are set from the durations in PlayerConfig rather than
        /// picked, so a clip finishes as its state does instead of holding its
        /// last frame or being cut off mid-way.
        /// </summary>
        private static SpriteAnimationSet CreateAnimationSet(PlayerConfig config)
        {
            var set = ScriptableObject.CreateInstance<SpriteAnimationSet>();

            Sprite[] idle = PlayerAnimationImport.Frames("Idle");
            Sprite[] run = PlayerAnimationImport.Frames("Run");
            Sprite[] jump = PlayerAnimationImport.Frames("Jump");
            Sprite[] flipJump = PlayerAnimationImport.Frames("FlipJump");
            Sprite[] bigJump = PlayerAnimationImport.Frames("BigJump");
            Sprite[] lowFlip = PlayerAnimationImport.Frames("LowFlip");
            Sprite[] fall = PlayerAnimationImport.Frames("Fall");
            Sprite[] tackle = PlayerAnimationImport.Frames("Tackle");

            // Whatever we can stand on if a folder is missing: the hand-made
            // runner, then the generated silhouette.
            Sprite still = PlayerAnimationImport.Frame("Idle", 0)
                           ?? ArtImport.Load("runner")
                           ?? PlaceholderArt.Load("runner");

            Sprite[] held = { still };

            // A rate that spreads the frames across the state's own duration.
            float Over(float seconds, Sprite[] frames)
            {
                return frames.Length > 1 ? frames.Length / Mathf.Max(0.05f, seconds) : 12f;
            }

            // How long a rise actually lasts. TickAirborne swaps to Falling the
            // moment upward speed reaches zero, and the driver changes clip with
            // it - so a rise clip has until the apex and not a frame longer. The
            // somersault is eight frames against a 0.38s rise; at a hand-picked
            // 14fps it would be cut off three frames short of landing upright,
            // every single jump.
            float RiseTime(float height)
            {
                float gravity = Mathf.Abs(Physics2D.gravity.y) * config.riseGravity;
                return gravity > 0.01f ? config.JumpVelocityFor(height) / gravity : 0.4f;
            }

            float groundRise = RiseTime(config.jumpHeight);
            float airRise = RiseTime(config.doubleJumpHeight);

            // One full stride cycle - two footfalls - in half a second. That is
            // not a look-at-it-and-pick number: at the 9 the runner starts a
            // level on, it puts a footfall every 2.25 units against a figure
            // 1.80 tall, which is about the 1.2x height a person covers per step
            // at a run. Spread across however many frames the folder holds, so
            // redrawing the cycle smoother changes how finely it is sampled and
            // not how fast the runner appears to be moving. At 16 frames that is
            // 32fps; the same 0.5s it was at 8 frames and 16fps.
            const float strideCycle = 0.5f;

            SpriteAnimationClip Clip(PlayerAnim anim, Sprite[] frames, float fps, bool loop)
            {
                return new SpriteAnimationClip
                {
                    anim = anim,
                    frames = frames != null && frames.Length > 0 ? frames : held,
                    fps = fps,
                    loop = loop
                };
            }

            set.fallback = Clip(PlayerAnim.Idle, held, 1f, true);

            var clips = new List<SpriteAnimationClip>
            {
                // --- drawn as flip-books -----------------------------------
                Clip(PlayerAnim.Idle, idle, 8f, true),
                Clip(PlayerAnim.Run, run, Over(strideCycle, run), true),
                Clip(PlayerAnim.JumpRise, jump, Over(groundRise, jump), false),
                Clip(PlayerAnim.DoubleJump, bigJump, Over(airRise, bigJump), false),
                Clip(PlayerAnim.JumpFall, fall, 10f, true),

                // The somersault, over something small. Picked instead of
                // JumpRise - not alongside it - when the sensors see a low
                // obstacle within four units of a ground jump.
                Clip(PlayerAnim.LowFlip, lowFlip, Over(groundRise, lowFlip), false),

                // The dive reads as both the slide and the hard-landing roll -
                // same pose along the ground, different lengths of time in it.
                Clip(PlayerAnim.Slide, tackle, Over(config.slideDuration, tackle), false),
                Clip(PlayerAnim.Roll, tackle, Over(config.rollDuration, tackle), false),

                // --- single poses, left to the procedural tricks ------------
                // Nothing was drawn for these four, and a held pose is the way
                // to say so: the trick set spins the vault, leans the wall run
                // and hauls the runner over the ledge.
                Clip(PlayerAnim.Vault, new[] { PlayerAnimationImport.Frame("Jump", 1) ?? still }, 12f, false),
                Clip(PlayerAnim.WallRun, new[] { PlayerAnimationImport.Frame("Run", 3) ?? still }, 12f, true),
                Clip(PlayerAnim.LedgeGrab, new[] { PlayerAnimationImport.Frame("Fall", 1) ?? still }, 12f, false),
                Clip(PlayerAnim.LedgeClimb, new[] { PlayerAnimationImport.Frame("BigJump", 2) ?? still }, 12f, false),

                // The last frame of the dive, held: face down and not getting up.
                Clip(PlayerAnim.Death, new[] { PlayerAnimationImport.Frame("Tackle", 5) ?? still }, 12f, false)
            };

            // --- variants: a second clip on a slot already filled -------------
            //
            // SpriteAnimationSet.Get picks at random between every clip on a
            // slot, so adding the somersault to both jumps is all it takes for
            // repeated jumps to stop looking canned - sometimes the plain rise,
            // sometimes the flip, on the ground jump and the air jump alike.
            //
            // Guarded, unlike the slots above, because the two cases differ. An
            // empty slot wants the held pose so the runner still draws; an empty
            // *variant* would put that held pose into the draw against a real
            // clip, and every other jump would freeze on one frame.
            if (flipJump.Length > 1)
            {
                clips.Add(Clip(PlayerAnim.JumpRise, flipJump, Over(groundRise, flipJump), false));
                clips.Add(Clip(PlayerAnim.DoubleJump, flipJump, Over(airRise, flipJump), false));
            }

            set.clips = clips.ToArray();

            if (!PlayerAnimationImport.IsAvailable)
            {
                Debug.LogWarning("[ArvinRunner] No drawn player frames were found, so every slot is " +
                                 "holding one pose and the runner is animated procedurally. Check " +
                                 $"{PlayerAnimationImport.RootFolder}.");
            }

            return EditorUtil.CreateAsset(set, $"{DataFolder}/PlayerAnimations.asset");
        }

        // ---- Procedural tricks --------------------------------------------- //

        private static AnimationCurve Flat(float value) => AnimationCurve.Constant(0f, 1f, value);
        private static AnimationCurve Ease(float from, float to) => AnimationCurve.EaseInOut(0f, from, 1f, to);

        /// <summary>Rises to a peak in the middle and settles back.</summary>
        private static AnimationCurve Hump(float ends, float peak)
        {
            var curve = new AnimationCurve(
                new Keyframe(0f, ends), new Keyframe(0.5f, peak), new Keyframe(1f, ends));

            for (int i = 0; i < curve.length; i++) curve.SmoothTangents(i, 0f);
            return curve;
        }

        /// <summary>Snaps to a value and eases back - good for a landing squash.</summary>
        private static AnimationCurve Punch(float hit, float rest)
        {
            var curve = new AnimationCurve(
                new Keyframe(0f, hit), new Keyframe(0.35f, rest), new Keyframe(1f, rest));

            for (int i = 0; i < curve.length; i++) curve.SmoothTangents(i, 0f);
            return curve;
        }

        /// <summary>
        /// The runner's move list. Several states carry more than one variant,
        /// and one is drawn at random each time the state is entered - so a
        /// double jump alternates between a front flip, a back flip and a
        /// corkscrew instead of looking canned.
        ///
        /// Facing is +X, so a NEGATIVE spin rotates forwards (clockwise).
        /// </summary>
        private static TrickSet CreateTrickSet()
        {
            var set = ScriptableObject.CreateInstance<TrickSet>();

            set.clips = new[]
            {
                // ---- grounded -------------------------------------------- //
                new TrickClip
                {
                    name = "idle_breathe", anim = PlayerAnim.Idle, duration = 2.2f, loop = true,
                    squash = Hump(1f, 1.02f), squashCounter = 0.4f,
                    spin = Flat(0f)
                },
                new TrickClip
                {
                    name = "run_stride", anim = PlayerAnim.Run, duration = 0.30f, loop = true,
                    leanDegrees = -5f, spin = Flat(0f),
                    squash = Hump(1f, 0.96f), squashCounter = 0.5f,
                    offset = new Vector2(0f, 0.08f), offsetCurve = Hump(0f, 1f)
                },
                new TrickClip
                {
                    name = "run_drive", anim = PlayerAnim.Run, duration = 0.34f, loop = true,
                    leanDegrees = -8f, spin = Flat(0f),
                    squash = Hump(1f, 0.94f), squashCounter = 0.6f,
                    offset = new Vector2(0f, 0.10f), offsetCurve = Hump(0f, 1f)
                },

                // ---- jumping --------------------------------------------- //
                new TrickClip
                {
                    name = "jump_rise", anim = PlayerAnim.JumpRise, duration = 0.28f,
                    leanDegrees = -14f, spin = Flat(0f),
                    squash = Punch(1.16f, 1.04f), squashCounter = 0.8f
                },
                new TrickClip
                {
                    name = "jump_fall", anim = PlayerAnim.JumpFall, duration = 0.25f,
                    leanDegrees = 7f, spin = Flat(0f),
                    squash = Ease(1.04f, 0.97f), squashCounter = 0.6f
                },

                // The air jump is the showpiece - three ways to spin it.
                new TrickClip
                {
                    name = "air_frontflip", anim = PlayerAnim.DoubleJump, duration = 0.45f,
                    spinDegrees = -360f, spin = AnimationCurve.Linear(0f, 0f, 1f, 1f),
                    squash = Hump(1f, 0.90f), squashCounter = 0.5f
                },
                new TrickClip
                {
                    name = "air_backflip", anim = PlayerAnim.DoubleJump, duration = 0.50f,
                    spinDegrees = 360f, spin = AnimationCurve.Linear(0f, 0f, 1f, 1f),
                    squash = Hump(1f, 0.92f), squashCounter = 0.5f
                },
                new TrickClip
                {
                    name = "air_corkscrew", anim = PlayerAnim.DoubleJump, duration = 0.58f,
                    spinDegrees = -720f, spin = Ease(0f, 1f),
                    squash = Hump(1f, 0.88f), squashCounter = 0.6f
                },

                // ---- going low -------------------------------------------- //
                new TrickClip
                {
                    name = "slide_feet_first", anim = PlayerAnim.Slide, duration = 0.16f,
                    leanDegrees = 58f, spin = Flat(0f),
                    squash = Ease(1f, 0.74f), squashCounter = 0.9f,
                    // Lifted to offset the sink a 58 degree lean causes when the
                    // body rotates about its centre.
                    offset = new Vector2(0.05f, 0.22f), offsetCurve = Ease(0f, 1f)
                },
                new TrickClip
                {
                    name = "slide_dive", anim = PlayerAnim.Slide, duration = 0.18f,
                    leanDegrees = -72f, spin = Flat(0f),
                    squash = Ease(1f, 0.80f), squashCounter = 0.7f,
                    offset = new Vector2(0.12f, 0.13f), offsetCurve = Ease(0f, 1f)
                },
                new TrickClip
                {
                    name = "roll_forward", anim = PlayerAnim.Roll, duration = 0.48f,
                    spinDegrees = -360f, spin = AnimationCurve.Linear(0f, 0f, 1f, 1f),
                    squash = Ease(0.84f, 1f), squashCounter = 0.8f,
                    // A grounded spin needs clearance or the sprite scrapes
                    // through the floor at the halfway point.
                    offset = new Vector2(0f, 0.34f), offsetCurve = Hump(0f, 1f)
                },

                // ---- parkour ---------------------------------------------- //
                new TrickClip
                {
                    name = "vault_swing", anim = PlayerAnim.Vault, duration = 0.34f,
                    leanDegrees = -38f, spin = Flat(0f),
                    squash = Hump(1f, 0.92f), squashCounter = 0.6f,
                    offset = new Vector2(0f, 0.14f), offsetCurve = Hump(0f, 1f)
                },
                new TrickClip
                {
                    name = "vault_kong_flip", anim = PlayerAnim.Vault, duration = 0.34f,
                    spinDegrees = -360f, spin = AnimationCurve.Linear(0f, 0f, 1f, 1f),
                    squash = Hump(1f, 0.90f), squashCounter = 0.6f
                },
                new TrickClip
                {
                    name = "wall_run", anim = PlayerAnim.WallRun, duration = 0.26f, loop = true,
                    leanDegrees = -34f, spin = Flat(0f),
                    squash = Hump(1f, 0.97f), squashCounter = 0.4f,
                    offset = new Vector2(0.05f, 0.05f), offsetCurve = Hump(0f, 1f)
                },
                new TrickClip
                {
                    name = "ledge_hang", anim = PlayerAnim.LedgeGrab, duration = 0.18f,
                    leanDegrees = -6f, spin = Flat(0f),
                    squash = Ease(1f, 1.05f), squashCounter = 0.7f,
                    offset = new Vector2(0f, -0.12f), offsetCurve = Ease(0f, 1f)
                },
                new TrickClip
                {
                    name = "ledge_climb", anim = PlayerAnim.LedgeClimb, duration = 0.45f,
                    leanDegrees = -26f, spin = Flat(0f),
                    squash = Hump(1f, 0.93f), squashCounter = 0.5f,
                    offset = new Vector2(0f, 0.18f), offsetCurve = Hump(0f, 1f)
                },

                // ---- the end ---------------------------------------------- //
                new TrickClip
                {
                    name = "death_tumble", anim = PlayerAnim.Death, duration = 0.9f,
                    spinDegrees = 540f, spin = Ease(0f, 1f),
                    squash = Ease(1f, 0.88f), squashCounter = 0.5f
                },
                new TrickClip
                {
                    name = "death_faceplant", anim = PlayerAnim.Death, duration = 0.7f,
                    spinDegrees = -430f, spin = Ease(0f, 1f),
                    squash = Ease(1f, 0.85f), squashCounter = 0.6f
                }
            };

            return EditorUtil.CreateAsset(set, $"{DataFolder}/PlayerTricks.asset");
        }

        private static ParallaxTheme CreateTheme(string assetName, Color sky, Color tint)
        {
            var theme = ScriptableObject.CreateInstance<ParallaxTheme>();
            theme.skyColour = sky;

            theme.layers = new[]
            {
                new ParallaxLayerDef
                {
                    name = "Sky", sprite = PlaceholderArt.Load("sky"),
                    parallax = 0f, verticalParallax = 0.9f, yOffset = 0f,
                    sortingOrder = -300, tint = tint, heightOverride = 30f
                },
                new ParallaxLayerDef
                {
                    name = "Far", sprite = PlaceholderArt.Load("skyline_far"),
                    parallax = 0.25f, verticalParallax = 0.75f, yOffset = -2f,
                    sortingOrder = -200, tint = tint, autoScrollSpeed = 0.15f
                },
                new ParallaxLayerDef
                {
                    name = "Mid", sprite = PlaceholderArt.Load("skyline_mid"),
                    parallax = 0.5f, verticalParallax = 0.55f, yOffset = -4f,
                    sortingOrder = -150, tint = tint
                },
                new ParallaxLayerDef
                {
                    name = "Near", sprite = PlaceholderArt.Load("skyline_near"),
                    parallax = 0.75f, verticalParallax = 0.35f, yOffset = -7f,
                    sortingOrder = -100, tint = tint
                }
            };

            return EditorUtil.CreateAsset(theme, $"{DataFolder}/{assetName}.asset");
        }

        // ================================================================= //
        // Prefabs
        // ================================================================= //

        private static GameObject CreatePlayerPrefab(PlayerConfig config, SpriteAnimationSet animations,
                                                     TrickSet tricks)
        {
            var root = new GameObject("Player") { layer = GameLayers.Player };

            var body = root.AddComponent<Rigidbody2D>();
            body.gravityScale = config.riseGravity;
            body.freezeRotation = true;
            body.collisionDetectionMode = CollisionDetectionMode2D.Continuous;
            body.interpolation = RigidbodyInterpolation2D.Interpolate;

            const float height = 1.75f;
            const float width = 0.8f;

            var capsule = root.AddComponent<CapsuleCollider2D>();
            capsule.direction = CapsuleDirection2D.Vertical;
            capsule.size = new Vector2(width, height);
            capsule.offset = new Vector2(0f, height * 0.5f);   // pivot at the feet

            var material = new PhysicsMaterial2D("PlayerFrictionless") { friction = 0f, bounciness = 0f };
            EditorUtil.CreateAsset(material, $"{DataFolder}/PlayerFrictionless.physicsMaterial2D");
            capsule.sharedMaterial = material;

            // Two nested objects, because spinning and squashing need different
            // origins. "Visual" sits at the body centre and carries the rotation,
            // so a 360 reads as a somersault rather than the sprite pivoting on
            // its heels. "Sprite" hangs below it at the feet and carries the
            // squash, so the runner stays planted on the ground.
            var visual = new GameObject("Visual") { layer = GameLayers.Player };
            visual.transform.SetParent(root.transform, false);
            visual.transform.localPosition = new Vector3(0f, height * 0.5f, 0f);

            var spriteObject = new GameObject("Sprite") { layer = GameLayers.Player };
            spriteObject.transform.SetParent(visual.transform, false);

            // The first idle frame, so the prefab looks right in the inspector
            // before anything has played. Both it and the older single-pose
            // runner are imported with their pivot on the figure's feet, so the
            // sprite hangs a half-height below the body centre; only the
            // generated placeholder is centred on itself.
            Sprite runner = PlayerAnimationImport.Frame("Idle", 0) ?? ArtImport.Load("runner");

            spriteObject.transform.localPosition = runner != null
                ? new Vector3(0f, -height * 0.5f, 0f)
                : Vector3.zero;

            var renderer = spriteObject.AddComponent<SpriteRenderer>();
            renderer.sprite = runner ?? PlaceholderArt.Load("runner");
            renderer.sortingOrder = 20;

            var driver = visual.AddComponent<PlayerAnimatorDriver>();
            EditorUtil.SetObject(driver, "spriteRenderer", renderer);
            EditorUtil.SetObject(driver, "animationSet", animations);
            EditorUtil.SetObject(driver, "trickSet", tricks);

            root.AddComponent<PlayerSensors>();

            var controller = root.AddComponent<PlayerController>();
            EditorUtil.SetObject(controller, "config", config);
            EditorUtil.SetObject(controller, "animator", driver);

            return SavePrefab(root, $"{PrefabFolder}/Player.prefab");
        }

        private static GameObject CreatePadPrefab()
        {
            var root = new GameObject("GroundPad") { layer = GameLayers.Ground };
            root.AddComponent<BoxCollider2D>();

            var visual = new GameObject("Visual") { layer = GameLayers.Ground };
            visual.transform.SetParent(root.transform, false);

            var renderer = visual.AddComponent<SpriteRenderer>();
            renderer.sprite = PlaceholderArt.Load("box");
            renderer.drawMode = SpriteDrawMode.Tiled;
            renderer.tileMode = SpriteTileMode.Continuous;
            renderer.color = new Color(0.20f, 0.21f, 0.30f);
            renderer.sortingOrder = 5;

            var strip = root.AddComponent<GroundStrip>();
            EditorUtil.SetObject(strip, "body", renderer);
            EditorUtil.SetObject(strip, "box", root.GetComponent<BoxCollider2D>());
            strip.Resize(20f, 3f);

            return SavePrefab(root, $"{PrefabFolder}/GroundPad.prefab");
        }

        private static GameObject CreateFinishPrefab()
        {
            var root = new GameObject("FinishLine");

            // A chequered banner on a pole, not a solid slab. The old green
            // block read as a wall to jump rather than the goal to run through.
            var pole = new GameObject("Pole");
            pole.transform.SetParent(root.transform, false);
            pole.transform.localPosition = new Vector3(0f, 0f, 0f);

            var poleRenderer = pole.AddComponent<SpriteRenderer>();
            poleRenderer.sprite = PlaceholderArt.Load("box");
            poleRenderer.drawMode = SpriteDrawMode.Tiled;
            poleRenderer.tileMode = SpriteTileMode.Continuous;
            poleRenderer.size = new Vector2(0.18f, 6f);
            poleRenderer.color = new Color(0.85f, 0.87f, 0.92f, 0.9f);
            poleRenderer.sortingOrder = 11;

            var banner = new GameObject("Banner");
            banner.transform.SetParent(root.transform, false);
            banner.transform.localPosition = new Vector3(0.75f, 2.1f, 0f);

            var renderer = banner.AddComponent<SpriteRenderer>();
            renderer.sprite = PlaceholderArt.Load("finish");
            renderer.drawMode = SpriteDrawMode.Tiled;
            renderer.tileMode = SpriteTileMode.Continuous;
            renderer.size = new Vector2(1.5f, 0.9f);
            renderer.color = Color.white;
            renderer.sortingOrder = 12;

            var box = root.AddComponent<BoxCollider2D>();
            box.size = new Vector2(1.2f, 8f);
            box.isTrigger = true;

            root.AddComponent<FinishLine>();

            return SavePrefab(root, $"{PrefabFolder}/FinishLine.prefab");
        }

        private static GameObject CreateKillZonePrefab()
        {
            var root = new GameObject("KillZone");

            var box = root.AddComponent<BoxCollider2D>();
            box.size = new Vector2(400f, 4f);
            box.isTrigger = true;

            root.AddComponent<KillZone>();

            return SavePrefab(root, $"{PrefabFolder}/KillZone.prefab");
        }

        private static GameObject SavePrefab(GameObject root, string path)
        {
            EditorUtil.EnsureFolder(System.IO.Path.GetDirectoryName(path)?.Replace('\\', '/'));
            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
            return prefab;
        }

        // ================================================================= //
        // Levels
        // ================================================================= //

        private static LevelSet CreateLevels(LevelChunk[] chunks, ParallaxTheme night, ParallaxTheme dusk)
        {
            LevelChunk Find(string name)
            {
                foreach (LevelChunk c in chunks)
                    if (c != null && c.name == name) return c;

                Debug.LogWarning($"[ArvinRunner] Chunk '{name}' not found.");
                return null;
            }

            // Level 1 teaches one move at a time, with flat rooftop between each.
            LevelDefinition one = Sequenced(1, "First Steps",
                "Swipe up to jump, again in the air to flip. Swipe down to slide.",
                night, 45f,
                Find("Chunk_Flat"), Find("Chunk_Cones"), Find("Chunk_Skip"),
                Find("Chunk_Wreckers"), Find("Chunk_SlideGate"), Find("Chunk_Rails"),
                Find("Chunk_Flat"));

            LevelDefinition two = Sequenced(2, "Rooftops",
                "Not everything waits for you. Some of it is coming the other way.",
                night, 95f,
                Find("Chunk_Barriers"), Find("Chunk_Traffic"), Find("Chunk_Overpass"),
                Find("Chunk_Spikes"), Find("Chunk_Oncoming"), Find("Chunk_FenceLine"),
                Find("Chunk_WideGap"), Find("Chunk_StepsDown"), Find("Chunk_Flat"));

            LevelDefinition three = Sequenced(3, "Construction",
                "Jump into a wall to run up it, then grab the ledge.",
                dusk, 130f,
                Find("Chunk_StreetWorks"), Find("Chunk_DeliveryYard"), Find("Chunk_Collapsing"),
                Find("Chunk_WallClimb"), Find("Chunk_Crates"), Find("Chunk_ScaffoldTower"),
                Find("Chunk_AirStrike"), Find("Chunk_DigSite"), Find("Chunk_Scaffold"),
                Find("Chunk_Flat"));

            // Levels 4 and 5 are assembled from a pool - fast to make, fixed seed
            // so the layout is identical on every attempt.
            LevelDefinition four = Assembled(4, "Skyline", "Watch the beam rhythm before you commit.",
                dusk, 90f, chunks, 380f, seed: 4471,
                curve: AnimationCurve.Linear(0f, 2f, 1f, 4f));

            LevelDefinition five = Assembled(5, "Storm", "The wind will cut your jump short. Commit early.",
                night, 120f, chunks, 480f, seed: 8823,
                curve: AnimationCurve.EaseInOut(0f, 3f, 1f, 5f));

            var campaign = ScriptableObject.CreateInstance<LevelSet>();
            campaign.levels = new[] { one, two, three, four, five };
            return EditorUtil.CreateAsset(campaign, $"{DataFolder}/Campaign.asset");
        }

        private static LevelDefinition Sequenced(int number, string title, string hint,
                                                 ParallaxTheme theme, float parTime,
                                                 params LevelChunk[] order)
        {
            var level = ScriptableObject.CreateInstance<LevelDefinition>();
            level.levelNumber = number;
            level.displayName = title;
            level.hint = hint;
            level.mode = LevelDefinition.BuildMode.Sequenced;
            level.sequence = order;
            level.theme = theme;
            level.parTime = parTime;

            return EditorUtil.CreateAsset(level, $"{LevelFolder}/Level_{number:00}.asset");
        }

        private static LevelDefinition Assembled(int number, string title, string hint,
                                                 ParallaxTheme theme, float parTime,
                                                 LevelChunk[] pool, float length, int seed,
                                                 AnimationCurve curve)
        {
            var level = ScriptableObject.CreateInstance<LevelDefinition>();
            level.levelNumber = number;
            level.displayName = title;
            level.hint = hint;
            level.mode = LevelDefinition.BuildMode.Assembled;
            level.pool = pool;
            level.targetLength = length;
            level.seed = seed;
            level.difficultyCurve = curve;
            level.theme = theme;
            level.parTime = parTime;

            return EditorUtil.CreateAsset(level, $"{LevelFolder}/Level_{number:00}.asset");
        }

        // ================================================================= //
        // Scene
        // ================================================================= //

        private static void BuildScene(GameObject playerPrefab, GameObject padPrefab,
                                       GameObject finishPrefab, GameObject killZonePrefab,
                                       LevelSet campaign, ParallaxTheme theme)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // --- camera ----------------------------------------------------
            var cameraObject = new GameObject("Main Camera") { tag = "MainCamera" };
            var camera = cameraObject.AddComponent<Camera>();
            camera.orthographic = true;
            camera.orthographicSize = 7.5f;
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = theme.skyColour;
            camera.transform.position = new Vector3(0f, 3f, -10f);
            cameraObject.AddComponent<AudioListener>();

            var follow = cameraObject.AddComponent<CameraFollow>();

            // --- player ----------------------------------------------------
            var player = (GameObject)PrefabUtility.InstantiatePrefab(playerPrefab, scene);
            player.transform.position = new Vector3(0f, 2f, 0f);
            var controller = player.GetComponent<PlayerController>();

            EditorUtil.SetObject(follow, "target", player.transform);
            EditorUtil.SetObject(follow, "player", controller);

            // --- background ------------------------------------------------
            var backgroundObject = new GameObject("Background");
            var background = backgroundObject.AddComponent<ParallaxBackground>();
            EditorUtil.SetObject(background, "theme", theme);
            EditorUtil.SetObject(background, "camera", camera);

            // --- systems ---------------------------------------------------
            var systems = new GameObject("Game");
            systems.AddComponent<SwipeInput>();

            var builder = systems.AddComponent<LevelBuilder>();
            EditorUtil.SetObject(builder, "padPrefab", padPrefab.GetComponent<GroundStrip>());
            EditorUtil.SetObject(builder, "finishLinePrefab", finishPrefab.GetComponent<FinishLine>());
            EditorUtil.SetObject(builder, "killZonePrefab", killZonePrefab.GetComponent<KillZone>());

            MusicPlayer music = Music(AudioImport.GameplayTrack, 0.5f);

            var manager = systems.AddComponent<GameManager>();
            EditorUtil.SetObject(manager, "music", music);
            EditorUtil.SetObject(manager, "builder", builder);
            EditorUtil.SetObject(manager, "player", controller);
            EditorUtil.SetObject(manager, "cameraFollow", follow);
            EditorUtil.SetObject(manager, "background", background);
            EditorUtil.SetObject(manager, "campaign", campaign);

            // -1 means "ask the menu, then fall back to saved progress".
            EditorUtil.SetInt(manager, "startLevelIndex", -1);

            // --- interface -------------------------------------------------
            BuildHud();

            EditorUtil.EnsureFolder("Assets/Scenes");
            EditorSceneManager.SaveScene(scene, ScenePath);
        }

        /// <summary>
        /// The scene's looping track. Returns the player so the GameManager can
        /// be handed it, for levels that name their own music.
        ///
        /// Built even when the clip is missing - an AudioSource with nothing in
        /// it is harmless, and it means dropping a file into Assets/Audio and
        /// re-importing is all it takes to give a scene music later.
        /// </summary>
        private static MusicPlayer Music(string track, float volume)
        {
            var go = new GameObject("Music");

            var source = go.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.loop = true;

            AudioClip clip = AudioImport.Load(track);

            var music = go.AddComponent<MusicPlayer>();
            EditorUtil.SetObject(music, "clip", clip);
            EditorUtil.SetFloat(music, "volume", volume);

            if (clip == null)
                Debug.LogWarning($"[ArvinRunner] No '{track}' track, so that scene is silent. " +
                                 $"Drop one into {AudioImport.RootFolder} and build again.");

            return music;
        }

        /// <summary>
        /// Replaces the build scene list with exactly these, in this order. The
        /// menu has to be first so a player build boots into it.
        /// </summary>
        private static void SetBuildSettings(params string[] paths)
        {
            var scenes = new EditorBuildSettingsScene[paths.Length];
            for (int i = 0; i < paths.Length; i++)
                scenes[i] = new EditorBuildSettingsScene(paths[i], true);

            EditorBuildSettings.scenes = scenes;
        }

        // ================================================================= //
        // Main menu
        // ================================================================= //

        /// <summary>
        /// The front end. Deliberately its own scene rather than a panel inside
        /// the game, so nothing about a run has to be torn down to get back here.
        /// </summary>
        private static void BuildMainMenuScene(LevelSet campaign)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var cameraObject = new GameObject("Main Camera") { tag = "MainCamera" };
            var camera = cameraObject.AddComponent<Camera>();
            camera.orthographic = true;
            camera.orthographicSize = 7.5f;
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0.05f, 0.06f, 0.13f);
            camera.transform.position = new Vector3(0f, 0f, -10f);
            cameraObject.AddComponent<AudioListener>();

            // The same parallax city as the game, drifting behind the menu.
            var backgroundObject = new GameObject("Background");
            var background = backgroundObject.AddComponent<ParallaxBackground>();
            EditorUtil.SetObject(background, "theme",
                AssetDatabase.LoadAssetAtPath<ParallaxTheme>($"{DataFolder}/Theme_Night.asset"));
            EditorUtil.SetObject(background, "camera", camera);

            Music(AudioImport.MenuTrack, 0.6f);

            var eventSystem = new GameObject("EventSystem");
            eventSystem.AddComponent<EventSystem>();
            eventSystem.AddComponent<StandaloneInputModule>();

            var canvasObject = new GameObject("Menu");
            var canvas = canvasObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var scaler = canvasObject.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920f, 1080f);
            scaler.matchWidthOrHeight = 0.5f;

            canvasObject.AddComponent<GraphicRaycaster>();
            var controller = canvasObject.AddComponent<MainMenuController>();

            // ---- home ------------------------------------------------------
            GameObject home = Overlay(canvasObject, "HomePanel", new Color(0f, 0f, 0f, 0.35f));

            Label(home, "Title", CentreAnchor, CentreAnchor, new Vector2(0f, 260f),
                  new Vector2(1400f, 140f), "ARVIN RUNNER", 108, TextAnchor.MiddleCenter);
            Label(home, "Subtitle", CentreAnchor, CentreAnchor, new Vector2(0f, 170f),
                  new Vector2(1400f, 60f), "swipe up to jump  -  swipe down to slide",
                  34, TextAnchor.MiddleCenter);

            Button play = MakeButton(home, "PlayButton", new Vector2(0f, 30f), "Play");
            play.GetComponent<RectTransform>().sizeDelta = new Vector2(460f, 110f);
            Text playLabel = play.GetComponentInChildren<Text>();

            Button levels = MakeButton(home, "LevelsButton", new Vector2(0f, -100f), "Levels");
            levels.GetComponent<RectTransform>().sizeDelta = new Vector2(460f, 100f);

            Button quit = MakeButton(home, "QuitButton", new Vector2(0f, -230f), "Quit");
            quit.GetComponent<RectTransform>().sizeDelta = new Vector2(460f, 100f);

            Text pickups = Label(home, "PickupTotal", new Vector2(0.5f, 0f), new Vector2(0.5f, 0f),
                                 new Vector2(0f, 40f), new Vector2(800f, 50f),
                                 "0 collected", 30, TextAnchor.LowerCenter);

            // ---- level select ----------------------------------------------
            GameObject levelsPanel = Overlay(canvasObject, "LevelsPanel", new Color(0f, 0f, 0f, 0.55f));

            Label(levelsPanel, "LevelsTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 300f),
                  new Vector2(1400f, 100f), "SELECT LEVEL", 72, TextAnchor.MiddleCenter);

            var grid = new GameObject("Grid");
            grid.transform.SetParent(levelsPanel.transform, false);

            var gridRect = grid.AddComponent<RectTransform>();
            gridRect.anchorMin = CentreAnchor;
            gridRect.anchorMax = CentreAnchor;
            gridRect.pivot = CentreAnchor;
            gridRect.anchoredPosition = new Vector2(0f, 40f);
            gridRect.sizeDelta = new Vector2(1400f, 380f);

            var layout = grid.AddComponent<GridLayoutGroup>();
            layout.cellSize = new Vector2(230f, 180f);
            layout.spacing = new Vector2(26f, 26f);
            layout.childAlignment = TextAnchor.MiddleCenter;
            layout.constraint = GridLayoutGroup.Constraint.FixedColumnCount;
            layout.constraintCount = 5;

            // One button is built as a template; the controller clones it per level.
            Button template = MakeButton(grid, "LevelButtonTemplate", Vector2.zero, "1");
            Text templateNumber = template.GetComponentInChildren<Text>();
            templateNumber.fontSize = 64;
            templateNumber.alignment = TextAnchor.UpperCenter;

            Text templateCaption = Label(template.gameObject, "Caption",
                                         new Vector2(0.5f, 0f), new Vector2(0.5f, 0f),
                                         new Vector2(0f, 22f), new Vector2(220f, 40f),
                                         "", 24, TextAnchor.LowerCenter);
            templateCaption.color = new Color(1f, 1f, 1f, 0.7f);

            Button back = MakeButton(levelsPanel, "BackButton", new Vector2(-180f, -260f), "Back");
            Button reset = MakeButton(levelsPanel, "ResetButton", new Vector2(180f, -260f), "Reset");

            levelsPanel.SetActive(false);

            // ---- wiring ----------------------------------------------------
            EditorUtil.SetObject(controller, "campaign", campaign);
            EditorUtil.SetObject(controller, "homePanel", home);
            EditorUtil.SetObject(controller, "levelsPanel", levelsPanel);
            EditorUtil.SetObject(controller, "playButton", play);
            EditorUtil.SetObject(controller, "playLabel", playLabel);
            EditorUtil.SetObject(controller, "levelsButton", levels);
            EditorUtil.SetObject(controller, "quitButton", quit);
            EditorUtil.SetObject(controller, "totalPickupsText", pickups);
            EditorUtil.SetObject(controller, "levelGrid", gridRect);
            EditorUtil.SetObject(controller, "levelButtonTemplate", template);
            EditorUtil.SetObject(controller, "backButton", back);
            EditorUtil.SetObject(controller, "resetProgressButton", reset);

            EditorUtil.EnsureFolder("Assets/Scenes");
            EditorSceneManager.SaveScene(scene, MenuScenePath);
        }

        // ================================================================= //
        // HUD construction
        // ================================================================= //

        private static Font _font;

        private static Font DefaultFont()
        {
            if (_font != null) return _font;

            // Unity renamed the built-in font part way through the 2022 cycle.
            _font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf")
                    ?? Resources.GetBuiltinResource<Font>("Arial.ttf");

            return _font;
        }

        private static void BuildHud()
        {
            var eventSystem = new GameObject("EventSystem");
            eventSystem.AddComponent<EventSystem>();
            eventSystem.AddComponent<StandaloneInputModule>();

            var canvasObject = new GameObject("HUD");
            var canvas = canvasObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var scaler = canvasObject.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920f, 1080f);
            scaler.matchWidthOrHeight = 0.5f;

            canvasObject.AddComponent<GraphicRaycaster>();

            var hud = canvasObject.AddComponent<GameHUD>();

            // --- top bar ---------------------------------------------------
            Text levelText = Label(canvasObject, "LevelText", new Vector2(0f, 1f), new Vector2(0f, 1f),
                                   new Vector2(40f, -40f), new Vector2(600f, 60f),
                                   "1. Rooftops", 40, TextAnchor.UpperLeft);

            Text timeText = Label(canvasObject, "TimeText", new Vector2(0.5f, 1f), new Vector2(0.5f, 1f),
                                  new Vector2(0f, -40f), new Vector2(400f, 60f),
                                  "00:00.00", 44, TextAnchor.UpperCenter);

            Text pickupText = Label(canvasObject, "PickupText", new Vector2(1f, 1f), new Vector2(1f, 1f),
                                    new Vector2(-40f, -40f), new Vector2(300f, 60f),
                                    "0", 44, TextAnchor.UpperRight);

            // --- progress bar ----------------------------------------------
            GameObject track = Panel(canvasObject, "ProgressTrack", new Color(1f, 1f, 1f, 0.15f));
            RectTransform trackRect = track.GetComponent<RectTransform>();
            trackRect.anchorMin = new Vector2(0.5f, 1f);
            trackRect.anchorMax = new Vector2(0.5f, 1f);
            trackRect.pivot = new Vector2(0.5f, 1f);
            trackRect.anchoredPosition = new Vector2(0f, -110f);
            trackRect.sizeDelta = new Vector2(900f, 14f);

            GameObject fillObject = Panel(track, "ProgressFill", new Color(0.45f, 0.95f, 0.7f, 0.95f));
            RectTransform fillRect = fillObject.GetComponent<RectTransform>();
            fillRect.anchorMin = Vector2.zero;
            fillRect.anchorMax = Vector2.one;
            fillRect.offsetMin = Vector2.zero;
            fillRect.offsetMax = Vector2.zero;

            var fillImage = fillObject.GetComponent<Image>();
            fillImage.type = Image.Type.Filled;
            fillImage.fillMethod = Image.FillMethod.Horizontal;
            fillImage.fillAmount = 0f;

            // --- panels ----------------------------------------------------
            GameObject ready = Overlay(canvasObject, "ReadyPanel", new Color(0f, 0f, 0f, 0.35f));
            Label(ready, "ReadyTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 90f),
                  new Vector2(1200f, 90f), "TAP TO START", 72, TextAnchor.MiddleCenter);
            Text readyHint = Label(ready, "ReadyHint", CentreAnchor, CentreAnchor, new Vector2(0f, -10f),
                                   new Vector2(1200f, 120f), "", 36, TextAnchor.MiddleCenter);

            GameObject death = Overlay(canvasObject, "DeathPanel", new Color(0.25f, 0f, 0f, 0.55f));
            Label(death, "DeathTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 120f),
                  new Vector2(1200f, 90f), "RUN OVER", 72, TextAnchor.MiddleCenter);
            Text deathReason = Label(death, "DeathReason", CentreAnchor, CentreAnchor, new Vector2(0f, 40f),
                                     new Vector2(1200f, 60f), "", 36, TextAnchor.MiddleCenter);
            Button restart = MakeButton(death, "RestartButton", new Vector2(0f, -80f), "Retry");

            GameObject finish = Overlay(canvasObject, "FinishPanel", new Color(0f, 0.2f, 0.1f, 0.55f));
            Label(finish, "FinishTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 150f),
                  new Vector2(1200f, 90f), "LEVEL CLEAR", 72, TextAnchor.MiddleCenter);
            Text finishSummary = Label(finish, "FinishSummary", CentreAnchor, CentreAnchor, new Vector2(0f, 50f),
                                       new Vector2(1200f, 120f), "", 36, TextAnchor.MiddleCenter);
            Button next = MakeButton(finish, "NextButton", new Vector2(-180f, -90f), "Next Level");
            Button retry = MakeButton(finish, "RetryButton", new Vector2(180f, -90f), "Replay");

            GameObject pause = Overlay(canvasObject, "PausePanel", new Color(0f, 0f, 0f, 0.6f));
            Label(pause, "PauseTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 90f),
                  new Vector2(1200f, 90f), "PAUSED", 72, TextAnchor.MiddleCenter);
            Button resume = MakeButton(pause, "ResumeButton", new Vector2(-180f, -40f), "Resume");

            // A way out of the run from every panel that stops play.
            Button menuFromPause = MakeButton(pause, "MenuButton", new Vector2(180f, -40f), "Main Menu");
            Button menuFromDeath = MakeButton(death, "MenuButton", new Vector2(0f, -190f), "Main Menu");
            Button menuFromFinish = MakeButton(finish, "MenuButton", new Vector2(0f, -200f), "Main Menu");

            // Corner pause control, always live during a run.
            Button pauseButton = MakeButton(canvasObject, "PauseButton", Vector2.zero, "II");
            RectTransform pauseRect = pauseButton.GetComponent<RectTransform>();
            pauseRect.anchorMin = new Vector2(1f, 0f);
            pauseRect.anchorMax = new Vector2(1f, 0f);
            pauseRect.pivot = new Vector2(1f, 0f);
            pauseRect.anchoredPosition = new Vector2(-40f, 40f);
            pauseRect.sizeDelta = new Vector2(110f, 96f);

            ready.SetActive(false);
            death.SetActive(false);
            finish.SetActive(false);
            pause.SetActive(false);

            // --- wire it up ------------------------------------------------
            EditorUtil.SetObject(hud, "levelText", levelText);
            EditorUtil.SetObject(hud, "timeText", timeText);
            EditorUtil.SetObject(hud, "pickupText", pickupText);
            EditorUtil.SetObject(hud, "progressFill", fillImage);
            EditorUtil.SetObject(hud, "progressTrack", trackRect);

            EditorUtil.SetObject(hud, "readyPanel", ready);
            EditorUtil.SetObject(hud, "readyHintText", readyHint);
            EditorUtil.SetObject(hud, "deathPanel", death);
            EditorUtil.SetObject(hud, "deathReasonText", deathReason);
            EditorUtil.SetObject(hud, "finishPanel", finish);
            EditorUtil.SetObject(hud, "finishSummaryText", finishSummary);
            EditorUtil.SetObject(hud, "pausePanel", pause);

            EditorUtil.SetObject(hud, "restartButton", restart);
            EditorUtil.SetObject(hud, "nextLevelButton", next);
            EditorUtil.SetObject(hud, "retryFromFinishButton", retry);
            EditorUtil.SetObject(hud, "resumeButton", resume);
            EditorUtil.SetObject(hud, "pauseButton", pauseButton);

            EditorUtil.SetObjectArray(hud, "menuButtons",
                                      new Object[] { menuFromPause, menuFromDeath, menuFromFinish });
        }

        private static readonly Vector2 CentreAnchor = new Vector2(0.5f, 0.5f);

        private static Text Label(GameObject parent, string name, Vector2 anchorMin, Vector2 anchorMax,
                                  Vector2 position, Vector2 size, string content, int fontSize,
                                  TextAnchor alignment)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);

            var rect = go.AddComponent<RectTransform>();
            rect.anchorMin = anchorMin;
            rect.anchorMax = anchorMax;
            rect.pivot = new Vector2(anchorMin.x, anchorMax.y);
            rect.anchoredPosition = position;
            rect.sizeDelta = size;

            var text = go.AddComponent<Text>();
            text.font = DefaultFont();
            text.text = content;
            text.fontSize = fontSize;
            text.alignment = alignment;
            text.color = Color.white;
            text.raycastTarget = false;
            text.horizontalOverflow = HorizontalWrapMode.Wrap;
            text.verticalOverflow = VerticalWrapMode.Overflow;

            return text;
        }

        private static GameObject Panel(GameObject parent, string name, Color colour)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);
            go.AddComponent<RectTransform>();

            var image = go.AddComponent<Image>();
            image.color = colour;
            image.raycastTarget = false;

            return go;
        }

        /// <summary>A full-screen panel used for the start, death and finish screens.</summary>
        private static GameObject Overlay(GameObject parent, string name, Color colour)
        {
            GameObject go = Panel(parent, name, colour);

            var rect = go.GetComponent<RectTransform>();
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;

            go.GetComponent<Image>().raycastTarget = true;
            return go;
        }

        private static Button MakeButton(GameObject parent, string name, Vector2 position, string label)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);

            var rect = go.AddComponent<RectTransform>();
            rect.anchorMin = CentreAnchor;
            rect.anchorMax = CentreAnchor;
            rect.pivot = CentreAnchor;
            rect.anchoredPosition = position;
            rect.sizeDelta = new Vector2(320f, 96f);

            var image = go.AddComponent<Image>();
            image.color = new Color(1f, 1f, 1f, 0.18f);

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            var textObject = new GameObject("Label");
            textObject.transform.SetParent(go.transform, false);

            var textRect = textObject.AddComponent<RectTransform>();
            textRect.anchorMin = Vector2.zero;
            textRect.anchorMax = Vector2.one;
            textRect.offsetMin = Vector2.zero;
            textRect.offsetMax = Vector2.zero;

            var text = textObject.AddComponent<Text>();
            text.font = DefaultFont();
            text.text = label;
            text.fontSize = 38;
            text.alignment = TextAnchor.MiddleCenter;
            text.color = Color.white;
            text.raycastTarget = false;

            return button;
        }
    }
}
