using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace ArvinRunner.EditorTools
{
    /// <summary>
    /// One-click project build. Creates the layers, placeholder art, tuning
    /// assets, prefabs, chunk library, levels and a fully wired Game scene.
    ///
    /// Safe to run more than once - it overwrites what it generated before.
    /// </summary>
    public static class ArvinRunnerSetup
    {
        private const string DataFolder = "Assets/Data";
        private const string PrefabFolder = "Assets/Prefabs";
        private const string LevelFolder = "Assets/Data/Levels";
        private const string ScenePath = "Assets/Scenes/Game.unity";

        [MenuItem("ArvinRunner/Build Playable Project", priority = 0)]
        public static void BuildAll()
        {
            if (!EditorUtility.DisplayDialog(
                    "Build ArvinRunner",
                    "This generates placeholder art, prefabs, levels and a new Game scene.\n\n" +
                    "Anything previously generated by this tool is overwritten. Continue?",
                    "Build", "Cancel"))
                return;

            try
            {
                EditorUtility.DisplayProgressBar("ArvinRunner", "Setting up layers", 0.05f);
                EditorUtil.EnsureLayers();
                ConfigureProject();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Generating placeholder art", 0.12f);
                PlaceholderArt.GenerateAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Importing artwork", 0.2f);
                ArtImport.ImportAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Creating tuning assets", 0.3f);
                PlayerConfig config = CreatePlayerConfig();
                SpriteAnimationSet animations = CreateAnimationSet();
                ParallaxTheme night = CreateTheme("Theme_Night", new Color(0.05f, 0.06f, 0.13f), Color.white);
                ParallaxTheme dusk = CreateTheme("Theme_Dusk", new Color(0.16f, 0.09f, 0.14f),
                                                 new Color(1f, 0.82f, 0.72f));

                EditorUtility.DisplayProgressBar("ArvinRunner", "Building prefabs", 0.45f);
                GameObject player = CreatePlayerPrefab(config, animations);
                GameObject pad = CreatePadPrefab();
                GameObject finish = CreateFinishPrefab();
                GameObject killZone = CreateKillZonePrefab();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Building obstacle chunks", 0.6f);
                LevelChunk[] chunks = ChunkFactory.CreateAll();

                EditorUtility.DisplayProgressBar("ArvinRunner", "Authoring levels", 0.75f);
                LevelSet campaign = CreateLevels(chunks, night, dusk);

                EditorUtility.DisplayProgressBar("ArvinRunner", "Assembling the scene", 0.9f);
                BuildScene(player, pad, finish, killZone, campaign, night);

                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            Debug.Log("[ArvinRunner] Build complete. Open Assets/Scenes/Game.unity and press Play.");
            EditorUtility.DisplayDialog("ArvinRunner",
                "Done.\n\nAssets/Scenes/Game.unity is open and ready.\n\n" +
                "Editor controls: W / Up / Space to jump, S / Down to slide, " +
                "or drag the mouse like a swipe.", "Play");
        }

        [MenuItem("ArvinRunner/Reset Saved Progress", priority = 20)]
        public static void ResetProgress()
        {
            SaveData.ResetAll();
            Debug.Log("[ArvinRunner] Saved progress cleared.");
        }

        // ================================================================= //
        // Project settings
        // ================================================================= //

        private static void ConfigureProject()
        {
            Physics2D.gravity = new Vector2(0f, -9.81f);
            Physics2D.queriesStartInColliders = false;

            PlayerSettings.defaultInterfaceOrientation = UIOrientation.LandscapeLeft;
            PlayerSettings.allowedAutorotateToPortrait = false;
            PlayerSettings.allowedAutorotateToPortraitUpsideDown = false;
        }

        // ================================================================= //
        // Assets
        // ================================================================= //

        private static PlayerConfig CreatePlayerConfig()
        {
            var config = ScriptableObject.CreateInstance<PlayerConfig>();
            return EditorUtil.CreateAsset(config, $"{DataFolder}/PlayerConfig.asset");
        }

        /// <summary>
        /// An animation set with one empty slot per state, pre-filled with the
        /// placeholder runner so something shows up straight away.
        /// </summary>
        private static SpriteAnimationSet CreateAnimationSet()
        {
            var set = ScriptableObject.CreateInstance<SpriteAnimationSet>();

            // The hand-made runner if it has been imported, otherwise the
            // generated silhouette.
            Sprite runner = ArtImport.Load("runner") ?? PlaceholderArt.Load("runner");

            set.fallback = new SpriteAnimationClip
            {
                anim = PlayerAnim.Idle,
                frames = new[] { runner },
                fps = 1f,
                loop = true
            };

            var values = System.Enum.GetValues(typeof(PlayerAnim));
            var clips = new List<SpriteAnimationClip>();

            foreach (PlayerAnim anim in values)
            {
                clips.Add(new SpriteAnimationClip
                {
                    anim = anim,
                    frames = new[] { runner },   // replace with your own frames
                    fps = 12f,
                    loop = anim == PlayerAnim.Idle || anim == PlayerAnim.Run || anim == PlayerAnim.WallRun
                });
            }

            set.clips = clips.ToArray();
            return EditorUtil.CreateAsset(set, $"{DataFolder}/PlayerAnimations.asset");
        }

        private static ParallaxTheme CreateTheme(string assetName, Color sky, Color tint)
        {
            var theme = ScriptableObject.CreateInstance<ParallaxTheme>();
            theme.skyColour = sky;

            theme.layers = new[]
            {
                new ParallaxLayerDef
                {
                    name = "Sky", sprite = PlaceholderArt.Load("sky"),
                    parallax = 0f, verticalParallax = 0.9f, yOffset = 0f,
                    sortingOrder = -300, tint = tint, heightOverride = 30f
                },
                new ParallaxLayerDef
                {
                    name = "Far", sprite = PlaceholderArt.Load("skyline_far"),
                    parallax = 0.25f, verticalParallax = 0.75f, yOffset = -2f,
                    sortingOrder = -200, tint = tint, autoScrollSpeed = 0.15f
                },
                new ParallaxLayerDef
                {
                    name = "Mid", sprite = PlaceholderArt.Load("skyline_mid"),
                    parallax = 0.5f, verticalParallax = 0.55f, yOffset = -4f,
                    sortingOrder = -150, tint = tint
                },
                new ParallaxLayerDef
                {
                    name = "Near", sprite = PlaceholderArt.Load("skyline_near"),
                    parallax = 0.75f, verticalParallax = 0.35f, yOffset = -7f,
                    sortingOrder = -100, tint = tint
                }
            };

            return EditorUtil.CreateAsset(theme, $"{DataFolder}/{assetName}.asset");
        }

        // ================================================================= //
        // Prefabs
        // ================================================================= //

        private static GameObject CreatePlayerPrefab(PlayerConfig config, SpriteAnimationSet animations)
        {
            var root = new GameObject("Player") { layer = GameLayers.Player };

            var body = root.AddComponent<Rigidbody2D>();
            body.gravityScale = config.riseGravity;
            body.freezeRotation = true;
            body.collisionDetectionMode = CollisionDetectionMode2D.Continuous;
            body.interpolation = RigidbodyInterpolation2D.Interpolate;

            const float height = 1.75f;
            const float width = 0.8f;

            var capsule = root.AddComponent<CapsuleCollider2D>();
            capsule.direction = CapsuleDirection2D.Vertical;
            capsule.size = new Vector2(width, height);
            capsule.offset = new Vector2(0f, height * 0.5f);   // pivot at the feet

            var material = new PhysicsMaterial2D("PlayerFrictionless") { friction = 0f, bounciness = 0f };
            EditorUtil.CreateAsset(material, $"{DataFolder}/PlayerFrictionless.physicsMaterial2D");
            capsule.sharedMaterial = material;

            var visual = new GameObject("Visual") { layer = GameLayers.Player };
            visual.transform.SetParent(root.transform, false);

            Sprite runner = ArtImport.Load("runner");

            // The imported runner has a bottom-centre pivot, so it sits at the
            // capsule's base. The generated placeholder is centred, so it needs
            // lifting by half its height.
            visual.transform.localPosition = runner != null
                ? Vector3.zero
                : new Vector3(0f, height * 0.5f, 0f);

            var renderer = visual.AddComponent<SpriteRenderer>();
            renderer.sprite = runner ?? PlaceholderArt.Load("runner");
            renderer.sortingOrder = 20;

            var driver = visual.AddComponent<PlayerAnimatorDriver>();
            EditorUtil.SetObject(driver, "animationSet", animations);

            root.AddComponent<PlayerSensors>();

            var controller = root.AddComponent<PlayerController>();
            EditorUtil.SetObject(controller, "config", config);
            EditorUtil.SetObject(controller, "animator", driver);

            return SavePrefab(root, $"{PrefabFolder}/Player.prefab");
        }

        private static GameObject CreatePadPrefab()
        {
            var root = new GameObject("GroundPad") { layer = GameLayers.Ground };
            root.AddComponent<BoxCollider2D>();

            var visual = new GameObject("Visual") { layer = GameLayers.Ground };
            visual.transform.SetParent(root.transform, false);

            var renderer = visual.AddComponent<SpriteRenderer>();
            renderer.sprite = PlaceholderArt.Load("box");
            renderer.drawMode = SpriteDrawMode.Tiled;
            renderer.tileMode = SpriteTileMode.Continuous;
            renderer.color = new Color(0.20f, 0.21f, 0.30f);
            renderer.sortingOrder = 5;

            var strip = root.AddComponent<GroundStrip>();
            EditorUtil.SetObject(strip, "body", renderer);
            EditorUtil.SetObject(strip, "box", root.GetComponent<BoxCollider2D>());
            strip.Resize(20f, 3f);

            return SavePrefab(root, $"{PrefabFolder}/GroundPad.prefab");
        }

        private static GameObject CreateFinishPrefab()
        {
            var root = new GameObject("FinishLine");

            // A chequered banner on a pole, not a solid slab. The old green
            // block read as a wall to jump rather than the goal to run through.
            var pole = new GameObject("Pole");
            pole.transform.SetParent(root.transform, false);
            pole.transform.localPosition = new Vector3(0f, 0f, 0f);

            var poleRenderer = pole.AddComponent<SpriteRenderer>();
            poleRenderer.sprite = PlaceholderArt.Load("box");
            poleRenderer.drawMode = SpriteDrawMode.Tiled;
            poleRenderer.tileMode = SpriteTileMode.Continuous;
            poleRenderer.size = new Vector2(0.18f, 6f);
            poleRenderer.color = new Color(0.85f, 0.87f, 0.92f, 0.9f);
            poleRenderer.sortingOrder = 11;

            var banner = new GameObject("Banner");
            banner.transform.SetParent(root.transform, false);
            banner.transform.localPosition = new Vector3(0.75f, 2.1f, 0f);

            var renderer = banner.AddComponent<SpriteRenderer>();
            renderer.sprite = PlaceholderArt.Load("finish");
            renderer.drawMode = SpriteDrawMode.Tiled;
            renderer.tileMode = SpriteTileMode.Continuous;
            renderer.size = new Vector2(1.5f, 0.9f);
            renderer.color = Color.white;
            renderer.sortingOrder = 12;

            var box = root.AddComponent<BoxCollider2D>();
            box.size = new Vector2(1.2f, 8f);
            box.isTrigger = true;

            root.AddComponent<FinishLine>();

            return SavePrefab(root, $"{PrefabFolder}/FinishLine.prefab");
        }

        private static GameObject CreateKillZonePrefab()
        {
            var root = new GameObject("KillZone");

            var box = root.AddComponent<BoxCollider2D>();
            box.size = new Vector2(400f, 4f);
            box.isTrigger = true;

            root.AddComponent<KillZone>();

            return SavePrefab(root, $"{PrefabFolder}/KillZone.prefab");
        }

        private static GameObject SavePrefab(GameObject root, string path)
        {
            EditorUtil.EnsureFolder(System.IO.Path.GetDirectoryName(path)?.Replace('\\', '/'));
            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
            return prefab;
        }

        // ================================================================= //
        // Levels
        // ================================================================= //

        private static LevelSet CreateLevels(LevelChunk[] chunks, ParallaxTheme night, ParallaxTheme dusk)
        {
            LevelChunk Find(string name)
            {
                foreach (LevelChunk c in chunks)
                    if (c != null && c.name == name) return c;

                Debug.LogWarning($"[ArvinRunner] Chunk '{name}' not found.");
                return null;
            }

            // Level 1 teaches one move at a time, with flat rooftop between each.
            LevelDefinition one = Sequenced(1, "First Steps",
                "Swipe up to jump. Swipe up again in the air for a double jump.",
                night, 42f,
                Find("Chunk_Flat"), Find("Chunk_Cones"), Find("Chunk_Skip"),
                Find("Chunk_SlideGate"), Find("Chunk_Gap"), Find("Chunk_Flat"));

            LevelDefinition two = Sequenced(2, "Rooftops",
                "Swipe down to slide. Land hard and you will roll.",
                night, 60f,
                Find("Chunk_Barriers"), Find("Chunk_Condensers"), Find("Chunk_Spikes"),
                Find("Chunk_WideGap"), Find("Chunk_StepsDown"), Find("Chunk_Flat"));

            LevelDefinition three = Sequenced(3, "Construction",
                "Jump into a wall to run up it, then grab the ledge.",
                dusk, 80f,
                Find("Chunk_StreetWorks"), Find("Chunk_Collapsing"), Find("Chunk_WallClimb"),
                Find("Chunk_Crates"), Find("Chunk_Trampoline"), Find("Chunk_Flat"));

            // Levels 4 and 5 are assembled from a pool - fast to make, fixed seed
            // so the layout is identical on every attempt.
            LevelDefinition four = Assembled(4, "Skyline", "Watch the beam rhythm before you commit.",
                dusk, 90f, chunks, 380f, seed: 4471,
                curve: AnimationCurve.Linear(0f, 2f, 1f, 4f));

            LevelDefinition five = Assembled(5, "Storm", "The wind will cut your jump short. Commit early.",
                night, 120f, chunks, 480f, seed: 8823,
                curve: AnimationCurve.EaseInOut(0f, 3f, 1f, 5f));

            var campaign = ScriptableObject.CreateInstance<LevelSet>();
            campaign.levels = new[] { one, two, three, four, five };
            return EditorUtil.CreateAsset(campaign, $"{DataFolder}/Campaign.asset");
        }

        private static LevelDefinition Sequenced(int number, string title, string hint,
                                                 ParallaxTheme theme, float parTime,
                                                 params LevelChunk[] order)
        {
            var level = ScriptableObject.CreateInstance<LevelDefinition>();
            level.levelNumber = number;
            level.displayName = title;
            level.hint = hint;
            level.mode = LevelDefinition.BuildMode.Sequenced;
            level.sequence = order;
            level.theme = theme;
            level.parTime = parTime;

            return EditorUtil.CreateAsset(level, $"{LevelFolder}/Level_{number:00}.asset");
        }

        private static LevelDefinition Assembled(int number, string title, string hint,
                                                 ParallaxTheme theme, float parTime,
                                                 LevelChunk[] pool, float length, int seed,
                                                 AnimationCurve curve)
        {
            var level = ScriptableObject.CreateInstance<LevelDefinition>();
            level.levelNumber = number;
            level.displayName = title;
            level.hint = hint;
            level.mode = LevelDefinition.BuildMode.Assembled;
            level.pool = pool;
            level.targetLength = length;
            level.seed = seed;
            level.difficultyCurve = curve;
            level.theme = theme;
            level.parTime = parTime;

            return EditorUtil.CreateAsset(level, $"{LevelFolder}/Level_{number:00}.asset");
        }

        // ================================================================= //
        // Scene
        // ================================================================= //

        private static void BuildScene(GameObject playerPrefab, GameObject padPrefab,
                                       GameObject finishPrefab, GameObject killZonePrefab,
                                       LevelSet campaign, ParallaxTheme theme)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // --- camera ----------------------------------------------------
            var cameraObject = new GameObject("Main Camera") { tag = "MainCamera" };
            var camera = cameraObject.AddComponent<Camera>();
            camera.orthographic = true;
            camera.orthographicSize = 7.5f;
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = theme.skyColour;
            camera.transform.position = new Vector3(0f, 3f, -10f);
            cameraObject.AddComponent<AudioListener>();

            var follow = cameraObject.AddComponent<CameraFollow>();

            // --- player ----------------------------------------------------
            var player = (GameObject)PrefabUtility.InstantiatePrefab(playerPrefab, scene);
            player.transform.position = new Vector3(0f, 2f, 0f);
            var controller = player.GetComponent<PlayerController>();

            EditorUtil.SetObject(follow, "target", player.transform);
            EditorUtil.SetObject(follow, "player", controller);

            // --- background ------------------------------------------------
            var backgroundObject = new GameObject("Background");
            var background = backgroundObject.AddComponent<ParallaxBackground>();
            EditorUtil.SetObject(background, "theme", theme);
            EditorUtil.SetObject(background, "camera", camera);

            // --- systems ---------------------------------------------------
            var systems = new GameObject("Game");
            systems.AddComponent<SwipeInput>();

            var builder = systems.AddComponent<LevelBuilder>();
            EditorUtil.SetObject(builder, "padPrefab", padPrefab.GetComponent<GroundStrip>());
            EditorUtil.SetObject(builder, "finishLinePrefab", finishPrefab.GetComponent<FinishLine>());
            EditorUtil.SetObject(builder, "killZonePrefab", killZonePrefab.GetComponent<KillZone>());

            var manager = systems.AddComponent<GameManager>();
            EditorUtil.SetObject(manager, "builder", builder);
            EditorUtil.SetObject(manager, "player", controller);
            EditorUtil.SetObject(manager, "cameraFollow", follow);
            EditorUtil.SetObject(manager, "background", background);
            EditorUtil.SetObject(manager, "campaign", campaign);

            // --- interface -------------------------------------------------
            BuildHud();

            EditorUtil.EnsureFolder("Assets/Scenes");
            EditorSceneManager.SaveScene(scene, ScenePath);
            AddSceneToBuildSettings(ScenePath);
        }

        private static void AddSceneToBuildSettings(string path)
        {
            var scenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);

            foreach (EditorBuildSettingsScene existing in scenes)
                if (existing.path == path) return;

            scenes.Insert(0, new EditorBuildSettingsScene(path, true));
            EditorBuildSettings.scenes = scenes.ToArray();
        }

        // ================================================================= //
        // HUD construction
        // ================================================================= //

        private static Font _font;

        private static Font DefaultFont()
        {
            if (_font != null) return _font;

            // Unity renamed the built-in font part way through the 2022 cycle.
            _font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf")
                    ?? Resources.GetBuiltinResource<Font>("Arial.ttf");

            return _font;
        }

        private static void BuildHud()
        {
            var eventSystem = new GameObject("EventSystem");
            eventSystem.AddComponent<EventSystem>();
            eventSystem.AddComponent<StandaloneInputModule>();

            var canvasObject = new GameObject("HUD");
            var canvas = canvasObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var scaler = canvasObject.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920f, 1080f);
            scaler.matchWidthOrHeight = 0.5f;

            canvasObject.AddComponent<GraphicRaycaster>();

            var hud = canvasObject.AddComponent<GameHUD>();

            // --- top bar ---------------------------------------------------
            Text levelText = Label(canvasObject, "LevelText", new Vector2(0f, 1f), new Vector2(0f, 1f),
                                   new Vector2(40f, -40f), new Vector2(600f, 60f),
                                   "1. Rooftops", 40, TextAnchor.UpperLeft);

            Text timeText = Label(canvasObject, "TimeText", new Vector2(0.5f, 1f), new Vector2(0.5f, 1f),
                                  new Vector2(0f, -40f), new Vector2(400f, 60f),
                                  "00:00.00", 44, TextAnchor.UpperCenter);

            Text pickupText = Label(canvasObject, "PickupText", new Vector2(1f, 1f), new Vector2(1f, 1f),
                                    new Vector2(-40f, -40f), new Vector2(300f, 60f),
                                    "0", 44, TextAnchor.UpperRight);

            // --- progress bar ----------------------------------------------
            GameObject track = Panel(canvasObject, "ProgressTrack", new Color(1f, 1f, 1f, 0.15f));
            RectTransform trackRect = track.GetComponent<RectTransform>();
            trackRect.anchorMin = new Vector2(0.5f, 1f);
            trackRect.anchorMax = new Vector2(0.5f, 1f);
            trackRect.pivot = new Vector2(0.5f, 1f);
            trackRect.anchoredPosition = new Vector2(0f, -110f);
            trackRect.sizeDelta = new Vector2(900f, 14f);

            GameObject fillObject = Panel(track, "ProgressFill", new Color(0.45f, 0.95f, 0.7f, 0.95f));
            RectTransform fillRect = fillObject.GetComponent<RectTransform>();
            fillRect.anchorMin = Vector2.zero;
            fillRect.anchorMax = Vector2.one;
            fillRect.offsetMin = Vector2.zero;
            fillRect.offsetMax = Vector2.zero;

            var fillImage = fillObject.GetComponent<Image>();
            fillImage.type = Image.Type.Filled;
            fillImage.fillMethod = Image.FillMethod.Horizontal;
            fillImage.fillAmount = 0f;

            // --- panels ----------------------------------------------------
            GameObject ready = Overlay(canvasObject, "ReadyPanel", new Color(0f, 0f, 0f, 0.35f));
            Label(ready, "ReadyTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 90f),
                  new Vector2(1200f, 90f), "TAP TO START", 72, TextAnchor.MiddleCenter);
            Text readyHint = Label(ready, "ReadyHint", CentreAnchor, CentreAnchor, new Vector2(0f, -10f),
                                   new Vector2(1200f, 120f), "", 36, TextAnchor.MiddleCenter);

            GameObject death = Overlay(canvasObject, "DeathPanel", new Color(0.25f, 0f, 0f, 0.55f));
            Label(death, "DeathTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 120f),
                  new Vector2(1200f, 90f), "RUN OVER", 72, TextAnchor.MiddleCenter);
            Text deathReason = Label(death, "DeathReason", CentreAnchor, CentreAnchor, new Vector2(0f, 40f),
                                     new Vector2(1200f, 60f), "", 36, TextAnchor.MiddleCenter);
            Button restart = MakeButton(death, "RestartButton", new Vector2(0f, -80f), "Retry");

            GameObject finish = Overlay(canvasObject, "FinishPanel", new Color(0f, 0.2f, 0.1f, 0.55f));
            Label(finish, "FinishTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 150f),
                  new Vector2(1200f, 90f), "LEVEL CLEAR", 72, TextAnchor.MiddleCenter);
            Text finishSummary = Label(finish, "FinishSummary", CentreAnchor, CentreAnchor, new Vector2(0f, 50f),
                                       new Vector2(1200f, 120f), "", 36, TextAnchor.MiddleCenter);
            Button next = MakeButton(finish, "NextButton", new Vector2(-180f, -90f), "Next Level");
            Button retry = MakeButton(finish, "RetryButton", new Vector2(180f, -90f), "Replay");

            GameObject pause = Overlay(canvasObject, "PausePanel", new Color(0f, 0f, 0f, 0.6f));
            Label(pause, "PauseTitle", CentreAnchor, CentreAnchor, new Vector2(0f, 90f),
                  new Vector2(1200f, 90f), "PAUSED", 72, TextAnchor.MiddleCenter);
            Button resume = MakeButton(pause, "ResumeButton", new Vector2(0f, -40f), "Resume");

            ready.SetActive(false);
            death.SetActive(false);
            finish.SetActive(false);
            pause.SetActive(false);

            // --- wire it up ------------------------------------------------
            EditorUtil.SetObject(hud, "levelText", levelText);
            EditorUtil.SetObject(hud, "timeText", timeText);
            EditorUtil.SetObject(hud, "pickupText", pickupText);
            EditorUtil.SetObject(hud, "progressFill", fillImage);
            EditorUtil.SetObject(hud, "progressTrack", trackRect);

            EditorUtil.SetObject(hud, "readyPanel", ready);
            EditorUtil.SetObject(hud, "readyHintText", readyHint);
            EditorUtil.SetObject(hud, "deathPanel", death);
            EditorUtil.SetObject(hud, "deathReasonText", deathReason);
            EditorUtil.SetObject(hud, "finishPanel", finish);
            EditorUtil.SetObject(hud, "finishSummaryText", finishSummary);
            EditorUtil.SetObject(hud, "pausePanel", pause);

            EditorUtil.SetObject(hud, "restartButton", restart);
            EditorUtil.SetObject(hud, "nextLevelButton", next);
            EditorUtil.SetObject(hud, "retryFromFinishButton", retry);
            EditorUtil.SetObject(hud, "resumeButton", resume);
        }

        private static readonly Vector2 CentreAnchor = new Vector2(0.5f, 0.5f);

        private static Text Label(GameObject parent, string name, Vector2 anchorMin, Vector2 anchorMax,
                                  Vector2 position, Vector2 size, string content, int fontSize,
                                  TextAnchor alignment)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);

            var rect = go.AddComponent<RectTransform>();
            rect.anchorMin = anchorMin;
            rect.anchorMax = anchorMax;
            rect.pivot = new Vector2(anchorMin.x, anchorMax.y);
            rect.anchoredPosition = position;
            rect.sizeDelta = size;

            var text = go.AddComponent<Text>();
            text.font = DefaultFont();
            text.text = content;
            text.fontSize = fontSize;
            text.alignment = alignment;
            text.color = Color.white;
            text.raycastTarget = false;
            text.horizontalOverflow = HorizontalWrapMode.Wrap;
            text.verticalOverflow = VerticalWrapMode.Overflow;

            return text;
        }

        private static GameObject Panel(GameObject parent, string name, Color colour)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);
            go.AddComponent<RectTransform>();

            var image = go.AddComponent<Image>();
            image.color = colour;
            image.raycastTarget = false;

            return go;
        }

        /// <summary>A full-screen panel used for the start, death and finish screens.</summary>
        private static GameObject Overlay(GameObject parent, string name, Color colour)
        {
            GameObject go = Panel(parent, name, colour);

            var rect = go.GetComponent<RectTransform>();
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;

            go.GetComponent<Image>().raycastTarget = true;
            return go;
        }

        private static Button MakeButton(GameObject parent, string name, Vector2 position, string label)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);

            var rect = go.AddComponent<RectTransform>();
            rect.anchorMin = CentreAnchor;
            rect.anchorMax = CentreAnchor;
            rect.pivot = CentreAnchor;
            rect.anchoredPosition = position;
            rect.sizeDelta = new Vector2(320f, 96f);

            var image = go.AddComponent<Image>();
            image.color = new Color(1f, 1f, 1f, 0.18f);

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            var textObject = new GameObject("Label");
            textObject.transform.SetParent(go.transform, false);

            var textRect = textObject.AddComponent<RectTransform>();
            textRect.anchorMin = Vector2.zero;
            textRect.anchorMax = Vector2.one;
            textRect.offsetMin = Vector2.zero;
            textRect.offsetMax = Vector2.zero;

            var text = textObject.AddComponent<Text>();
            text.font = DefaultFont();
            text.text = label;
            text.fontSize = 38;
            text.alignment = TextAnchor.MiddleCenter;
            text.color = Color.white;
            text.raycastTarget = false;

            return button;
        }
    }
}
